name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    name: Publish to RubyGems
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Publish to RubyGems
        uses: rubygems/release-gem@v1
        
